import { NextResponse } from 'next/server';
import { timingSafeEqual } from 'crypto';
import { connectToDatabase } from '../../../lib/mongoose';
import { Product, Category } from '../../../lib/models';

const LAUNDRY_CATEGORY = {
  id: 'laundry',
  name: 'Laundry Products',
  short: 'Laundry',
  icon: 'Sparkles',
  blurb: 'Washing powders and laundry solutions for homes and businesses.',
  accent: '#0891B2',
  status: 'active',
  displayOrder: 7,
};

const LAUNDRY_PRODUCTS = [
  // 1. Brite n'Shine Washing Powder (5kg, 10kg, 20kg, 25kg, 50kg)
  {
    id: 'demo-brite-shine-washing-powder-5kg',
    name: "Brite n' Shine Washing Powder — 5kg",
    cat: 'laundry',
    sub: 'Everyday laundry washing powder',
    price: 0,
    was: null,
    size: '5kg',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: "Brite n' Shine 5kg Washing Powder is a high-performance laundry detergent formulated for reliable, everyday cleaning across both machine and hand washing. Its active stain-lifting formula cuts through dirt, grease, food marks, and general soiling while remaining gentle on fabrics and colours, leaving every load fresh, bright, and hygienically clean. The 5kg pack is ideal for households, guesthouses, salons, and small offices that want a dependable supply without committing to bulk volumes. For B2B buyers, it offers a consistent, cost-effective entry size that is easy to store, easy to dispense, and proven on day-to-day laundry — a smart starting point before scaling up to our bulk packs.",
    benefits: ['Fresh, clean laundry every wash', 'Suitable for machine and hand washing', 'Effective on everyday stains', 'Gentle on fabrics'],
    sku: 'DEMO-LND-001',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    variants: [],
    media: [],
  },
  {
    id: 'demo-brite-shine-washing-powder-10kg',
    name: "Brite n' Shine Washing Powder — 10kg",
    cat: 'laundry',
    sub: 'Value-size laundry washing powder',
    price: 0,
    was: null,
    size: '10kg',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: "Brite n' Shine 10kg Washing Powder is a value-size laundry detergent built for homes and growing businesses that get through regular wash loads. The concentrated formula delivers powerful stain removal on everyday and stubborn marks, works in both top- and front-loading machines as well as hand washing, and rinses cleanly to leave laundry soft and fresh. The 10kg size is well suited to guesthouses, B&Bs, restaurants, salons, gyms, and small laundromats that need a longer-lasting supply at a lower cost per wash. For B2B customers, it strikes the balance between manageable pack size and bulk economy, helping reduce reorder frequency while keeping linen, uniforms, and towels consistently clean.",
    benefits: ['Value size for households and small businesses', 'Effective on tough stains', 'Suitable for machine and hand washing', 'Long-lasting supply'],
    sku: 'DEMO-LND-002',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    variants: [],
    media: [],
  },
  {
    id: 'demo-brite-shine-washing-powder-20kg',
    name: "Brite n' Shine Washing Powder — 20kg",
    cat: 'laundry',
    sub: 'Bulk laundry washing powder',
    price: 0,
    was: null,
    size: '20kg',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: "Brite n' Shine 20kg Washing Powder is a bulk laundry detergent engineered for high-volume cleaning where consistency and cost control matter. The heavy-duty formula tackles tough, ground-in stains, body soil, and grease across large and frequent loads, performing reliably in commercial and domestic machines as well as hand washing. The 20kg pack is ideal for hotels, lodges, hospitality groups, laundromats, schools, clinics, and cleaning contractors that process linen, towels, and uniforms in volume. For B2B buyers, bulk packaging lowers the cost per wash, cuts down on reordering, and ensures a dependable supply for operations that simply cannot run out of detergent.",
    benefits: ['Bulk pack for high-volume use', 'Cost-effective per wash', 'Powerful stain removal', 'Suitable for commercial laundry'],
    sku: 'DEMO-LND-003',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    variants: [],
    media: [],
  },
  {
    id: 'demo-brite-shine-washing-powder-25kg',
    name: "Brite n' Shine Washing Powder — 25kg",
    cat: 'laundry',
    sub: 'Heavy-duty bulk washing powder',
    price: 0,
    was: null,
    size: '25kg',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: "Brite n' Shine 25kg Washing Powder is a heavy-duty bulk detergent designed for demanding commercial laundry and large household use. Its strong, deep-cleaning formula is built to handle heavily soiled items such as overalls, workwear, kitchen linen, and industrial uniforms, lifting oil, grime, and stubborn stains while protecting fabric quality wash after wash. The 25kg pack suits factories, workshops, mines, farms, hospitality operators, and industrial laundries that deal with large, dirty loads on a daily basis. For B2B customers, this size delivers serious bulk value, a low cost per wash, and the cleaning power needed for tough, high-frequency laundry environments.",
    benefits: ['Heavy-duty formula for commercial use', 'Handles large laundry loads', 'Effective on overalls and workwear', 'Bulk value pricing'],
    sku: 'DEMO-LND-004',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    variants: [],
    media: [],
  },
  {
    id: 'demo-brite-shine-washing-powder-50kg',
    name: "Brite n' Shine Washing Powder — 50kg",
    cat: 'laundry',
    sub: 'Large bulk washing powder pack',
    price: 750,
    was: null,
    size: '50kg',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: "Brite n' Shine 50kg Washing Powder is our largest bulk pack, formulated for businesses and industrial operations that run laundry at scale. The powerful, high-yield formula removes tough stains, heavy soiling, and grease across continuous, large-capacity loads while remaining effective in commercial machines and hand washing alike. The 50kg size is the go-to choice for industrial laundries, hotels and resorts, hospitals and care facilities, mines, factories, and large cleaning contractors that need maximum supply with minimal reordering. For B2B buyers, this pack offers the lowest cost per wash in the range, significant bulk savings, and the assurance of a steady, uninterrupted detergent supply for high-throughput operations.",
    benefits: ['Largest pack for maximum value', 'Ideal for businesses and high-volume laundry', 'Powerful cleaning formula', 'Reduces cost per wash significantly'],
    sku: 'DEMO-LND-005',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    variants: [],
    media: [],
  },
  
  // 2. ABL Oxygen Bleach (5L, 10L, 20L, 25L)
  {
    id: 'demo-abl-oxygen-bleach-5l',
    name: 'ABL Oxygen Bleach — 5L',
    cat: 'laundry',
    sub: 'Color-safe oxygen bleach',
    price: 0,
    was: null,
    size: '5L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Professional active oxygen bleach formulated for color-safe stain removal and sanitizing in commercial laundries, guesthouses, and hotels.',
    benefits: ['Color-safe whitening', 'Removes organic stains', 'Sanitizes fabrics', 'Gentle on fibers'],
    sku: 'DEMO-LND-007',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-abl-oxygen-bleach-10l',
    name: 'ABL Oxygen Bleach — 10L',
    cat: 'laundry',
    sub: 'Color-safe oxygen bleach',
    price: 0,
    was: null,
    size: '10L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Professional active oxygen bleach formulated for color-safe stain removal and sanitizing in commercial laundries, guesthouses, and hotels.',
    benefits: ['Color-safe whitening', 'Removes organic stains', 'Sanitizes fabrics', 'Gentle on fibers'],
    sku: 'DEMO-LND-008',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-abl-oxygen-bleach-20l',
    name: 'ABL Oxygen Bleach — 20L',
    cat: 'laundry',
    sub: 'Color-safe oxygen bleach',
    price: 0,
    was: null,
    size: '20L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'High-efficiency active oxygen bleach for industrial and commercial laundry applications, restoring whites and colors in high-volume cycles.',
    benefits: ['High-efficiency whitening', 'Designed for commercial use', 'Lifts stubborn organic stains', 'Chlorine-free sanitizer'],
    sku: 'DEMO-LND-009',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-abl-oxygen-bleach-25l',
    name: 'ABL Oxygen Bleach — 25L',
    cat: 'laundry',
    sub: 'Color-safe oxygen bleach',
    price: 0,
    was: null,
    size: '25L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Bulk commercial-grade active oxygen bleach, optimized for industrial laundry systems to remove organic stains and sanitize fabrics safely.',
    benefits: ['Bulk industrial value', 'Restores colors and whites', 'Removes food & wine stains', 'Eco-friendly oxygen formula'],
    sku: 'DEMO-LND-010',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },

  // 3. FAB Softener (5L - existing, 10L, 20L, 25L)
  {
    id: 'demo-fab-softener-5l',
    name: 'FAB Softener — Fresh & Soft 5L',
    cat: 'laundry',
    sub: 'Fabric softener with long-lasting fragrance',
    price: 0,
    was: null,
    size: '5L',
    rating: 0,
    reviews: 0,
    badge: 'Bestseller',
    img: '/assets/products/fab-softener-1.jpg',
    desc: "FAB Softener Fresh & Soft 5L is a premium concentrated fabric softener that leaves laundry noticeably soft, fresh, and easy to iron, with a long-lasting fragrance that stays on linen and clothing between washes. Its fabric-protect, anti-static formula conditions fibres to reduce wear, creasing, and cling, and is safe for use across everyday fabrics in both machine and hand washing. Available in blue, pink, and lavender variants, the 5L size is ideal for households, guesthouses, hotels, salons, and laundromats that want professional-quality results and a premium finish on towels, bedding, and garments. For B2B customers, the concentrated 5L format delivers excellent value per load, dependable scent and softness, and a presentation-ready finish that elevates the guest and customer experience.",
    benefits: [
      'Extra softness on every wash',
      'Long-lasting fresh fragrance',
      'Fabric protect formula',
      'Anti-static — safe for all washes',
    ],
    sku: 'DEMO-LND-006',
    stock: 20,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [
      { id: 'fab-softener-1', type: 'image', url: '/assets/products/fab-softener-1.jpg', storageKey: null, altText: 'FAB Softener Fresh & Soft 5L blue twin pack', sortOrder: 0, isPrimary: true,  fileName: 'fab-softener-1.jpg', mimeType: 'image/jpeg', fileSize: 0, createdAt: 1781200000000 },
      { id: 'fab-softener-2', type: 'image', url: '/assets/products/fab-softener-2.jpg', storageKey: null, altText: 'FAB Softener pink and lavender 4-pack',     sortOrder: 1, isPrimary: false, fileName: 'fab-softener-2.jpg', mimeType: 'image/jpeg', fileSize: 0, createdAt: 1781200000000 },
      { id: 'fab-softener-3', type: 'image', url: '/assets/products/fab-softener-3.jpg', storageKey: null, altText: 'FAB Softener hero shot with features',    sortOrder: 2, isPrimary: false, fileName: 'fab-softener-3.jpg', mimeType: 'image/jpeg', fileSize: 0, createdAt: 1781200000000 },
      { id: 'fab-softener-4', type: 'image', url: '/assets/products/fab-softener-4.jpg', storageKey: null, altText: 'FAB Softener 8-pack lineup',              sortOrder: 3, isPrimary: false, fileName: 'fab-softener-4.jpg', mimeType: 'image/jpeg', fileSize: 0, createdAt: 1781200000000 },
    ],
  },
  {
    id: 'demo-fab-softener-10l',
    name: 'FAB Softener — Fresh & Soft 10L',
    cat: 'laundry',
    sub: 'Fabric softener with long-lasting fragrance',
    price: 0,
    was: null,
    size: '10L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Concentrated commercial fabric softener with a long-lasting, fresh fragrance. Formulated to reduce static, ease ironing, and soften linens in guesthouses and hotels.',
    benefits: ['Extra softness on every wash', 'Long-lasting fresh fragrance', 'Reduces wrinkles and static', 'Ideal for hospitality sheets'],
    sku: 'DEMO-LND-011',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-fab-softener-20l',
    name: 'FAB Softener — Fresh & Soft 20L',
    cat: 'laundry',
    sub: 'Fabric softener with long-lasting fragrance',
    price: 0,
    was: null,
    size: '20L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Industrial concentrated fabric softener, perfect for commercial laundries, hospitality groups, and school dorms requiring premium linen presentation.',
    benefits: ['Premium static protection', 'Softens heavy towels and linens', 'Highly cost-effective dosing', 'Clean, fresh fragrance profile'],
    sku: 'DEMO-LND-012',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-fab-softener-25l',
    name: 'FAB Softener — Fresh & Soft 25L',
    cat: 'laundry',
    sub: 'Fabric softener with long-lasting fragrance',
    price: 0,
    was: null,
    size: '25L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Heavy-duty bulk concentrated fabric softener designed for high-capacity industrial machines, offering lowest cost per wash and superior fabric conditioning.',
    benefits: ['Bulk industrial efficiency', 'Exceptional softness and scent', 'Anti-static fabric shield', 'Speeds up drying and ironing times'],
    sku: 'DEMO-LND-013',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },

  // 4. ABL Laundry Liquid (5L, 10L, 20L, 25L)
  {
    id: 'demo-abl-laundry-liquid-5l',
    name: 'ABL Laundry Liquid — 5L',
    cat: 'laundry',
    sub: 'Concentrated liquid laundry detergent',
    price: 0,
    was: null,
    size: '5L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'High-performance bulk liquid laundry detergent for automatic washing machines, delivering spotless and fresh results for guesthouses and salons.',
    benefits: ['Deep cleaning liquid action', 'Dissolves fully to prevent residue', 'Effective at all temperatures', 'Fresh, long-lasting scent'],
    sku: 'DEMO-LND-014',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-abl-laundry-liquid-10l',
    name: 'ABL Laundry Liquid — 10L',
    cat: 'laundry',
    sub: 'Concentrated liquid laundry detergent',
    price: 0,
    was: null,
    size: '10L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Premium commercial laundry liquid detergent, built to penetrate dirt and grease effectively while remaining gentle on fabrics. Ideal for hotels and B&Bs.',
    benefits: ['Penetrates deep grime', 'Fiber-protecting formula', 'Great for white and colored loads', 'Highly concentrated supply'],
    sku: 'DEMO-LND-015',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-abl-laundry-liquid-20l',
    name: 'ABL Laundry Liquid — 20L',
    cat: 'laundry',
    sub: 'Concentrated liquid laundry detergent',
    price: 0,
    was: null,
    size: '20L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Commercial-strength liquid detergent for high-capacity laundry services and hospitality, designed for superior stain removal and fabric care.',
    benefits: ['Superior grease-cutting formula', 'Low suds for front loaders', 'Optimizes clean cycles', 'Reduces detergent waste'],
    sku: 'DEMO-LND-016',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-abl-laundry-liquid-25l',
    name: 'ABL Laundry Liquid — 25L',
    cat: 'laundry',
    sub: 'Concentrated liquid laundry detergent',
    price: 0,
    was: null,
    size: '25L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Industrial laundry liquid detergent for commercial laundromats and large-scale facilities, providing outstanding cleaning efficiency in bulk sizing.',
    benefits: ['Industrial washing capacity', 'Excellent cost-per-wash value', 'Strips organic and food soils', 'Designed for dosing pumps'],
    sku: 'DEMO-LND-017',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },

  // 5. Overall Washing Powder (5kg, 10kg, 20kg, 25kg)
  {
    id: 'demo-overall-washing-powder-5kg',
    name: 'Overall Washing Powder — 5kg',
    cat: 'laundry',
    sub: 'Heavy-duty workwear washing powder',
    price: 0,
    was: null,
    size: '5kg',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Heavy-duty industrial washing powder formulated specifically to target and remove stubborn grease, grime, and oil from overalls and workwear.',
    benefits: ['Removes industrial oil and grease', 'Formulated for workwear fabrics', 'Removes soot, oil & ground-in dirt', 'Safe for heavy-duty cottons'],
    sku: 'DEMO-LND-018',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-overall-washing-powder-10kg',
    name: 'Overall Washing Powder — 10kg',
    cat: 'laundry',
    sub: 'Heavy-duty workwear washing powder',
    price: 0,
    was: null,
    size: '10kg',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Industrial-grade washing powder optimized for workshops, factories, and cleaning contractors processing heavily soiled work garments and uniforms.',
    benefits: ['Strips factory grease & soot', 'Cleans heavy canvas and denims', 'Maintains workwear durability', 'High concentration powder'],
    sku: 'DEMO-LND-019',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-overall-washing-powder-20kg',
    name: 'Overall Washing Powder — 20kg',
    cat: 'laundry',
    sub: 'Heavy-duty workwear washing powder',
    price: 0,
    was: null,
    size: '20kg',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Heavy-duty workwear washing powder in bulk format, engineered for industrial laundries and mining/factory environments to strip heavy soot and oil.',
    benefits: ['Heavy soot and oil stripper', 'Optimized for B2B contracts', 'Works in commercial washers', 'Low foaming for fast rinses'],
    sku: 'DEMO-LND-020',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-overall-washing-powder-25kg',
    name: 'Overall Washing Powder — 25kg',
    cat: 'laundry',
    sub: 'Heavy-duty workwear washing powder',
    price: 0,
    was: null,
    size: '25kg',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Ultimate bulk workwear washing powder for maximum industrial laundering efficiency, removing tough soil from heavy-duty fabrics.',
    benefits: ['Strips oil and carbon deposits', 'Maximum bulk efficiency', 'Tough on stains, gentle on seams', 'Ideal for mining & heavy engineering'],
    sku: 'DEMO-LND-021',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },

  // 6. Bio Brite n' Shine Auto Washing Powder (5kg, 10kg, 20kg, 25kg)
  {
    id: 'demo-bio-brite-shine-auto-washing-powder-5kg',
    name: "Bio Brite n' Shine Auto Washing Powder — 5kg",
    cat: 'laundry',
    sub: 'Bio-active automatic washing powder',
    price: 0,
    was: null,
    size: '5kg',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Premium bio-active automatic washing powder with enzymes for superior stain removal in front/top-loading commercial machines.',
    benefits: ['Bio-enzymatic stain removal', 'Designed for automatic machines', 'Lifts protein & biological stains', 'Leaves laundry sparkling clean'],
    sku: 'DEMO-LND-022',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-bio-brite-shine-auto-washing-powder-10kg',
    name: "Bio Brite n' Shine Auto Washing Powder — 10kg",
    cat: 'laundry',
    sub: 'Bio-active automatic washing powder',
    price: 0,
    was: null,
    size: '10kg',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Bio-enzymatic automatic washing powder for hotels, schools, and guesthouses, providing deep dirt extraction and fabric brightness.',
    benefits: ['Deep biological stain cleaning', 'Protects fabric fibers', 'Reduces graying of whites', 'Safe for color washes'],
    sku: 'DEMO-LND-023',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-bio-brite-shine-auto-washing-powder-20kg',
    name: "Bio Brite n' Shine Auto Washing Powder — 20kg",
    cat: 'laundry',
    sub: 'Bio-active automatic washing powder',
    price: 0,
    was: null,
    size: '20kg',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Bulk bio-active automatic washing powder engineered for laundry operations, ensuring removal of protein, blood, and food stains.',
    benefits: ['High enzyme activity', 'Bulk commercial packaging', 'Lifts starch, fat & grass marks', 'Maintains linen brightness'],
    sku: 'DEMO-LND-024',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-bio-brite-shine-auto-washing-powder-25kg',
    name: "Bio Brite n' Shine Auto Washing Powder — 25kg",
    cat: 'laundry',
    sub: 'Bio-active automatic washing powder',
    price: 0,
    was: null,
    size: '25kg',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Industrial-scale enzymatic automatic washing powder, delivering ultimate stain-fighting power and fabric restoration in high-frequency wash environments.',
    benefits: ['Ultimate enzymatic action', 'Perfect for heavy industrial washing', 'Restores soiled hospitality linens', 'Lowest cost per wash bulk size'],
    sku: 'DEMO-LND-025',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },

  // 7. Blood Stain Remover (5L, 10L, 20L, 25L)
  {
    id: 'demo-blood-stain-remover-5l',
    name: 'Blood Stain Remover — 5L',
    cat: 'laundry',
    sub: 'Targeted organic stain remover',
    price: 0,
    was: null,
    size: '5L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Specialist targeted stain remover for healthcare facilities, laundries, hotels, and guesthouses to effectively dissolve organic and blood stains.',
    benefits: ['Dissolves blood & protein', 'Safe for whites & fast colors', 'Excellent pre-wash spotter', 'Saves stained hospital sheets'],
    sku: 'DEMO-LND-026',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-blood-stain-remover-10l',
    name: 'Blood Stain Remover — 10L',
    cat: 'laundry',
    sub: 'Targeted organic stain remover',
    price: 0,
    was: null,
    size: '10L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Professional organic stain remover designed for hospitality and hospitals, lifting stubborn blood and protein soils cleanly.',
    benefits: ['Targets organic compound spots', 'Minimizes fabric damage', 'Used as pre-soak or spot treatment', 'Professional formulation'],
    sku: 'DEMO-LND-027',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-blood-stain-remover-20l',
    name: 'Blood Stain Remover — 20L',
    cat: 'laundry',
    sub: 'Targeted organic stain remover',
    price: 0,
    was: null,
    size: '20L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Industrial-grade organic soil remover, providing high-volume laundry facilities with a reliable solution for persistent organic staining.',
    benefits: ['Industrial-strength enzyme action', 'Efficient bulk spotter', 'Breaks down protein bonds', 'Safe on commercial polyester/cotton'],
    sku: 'DEMO-LND-028',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-blood-stain-remover-25l',
    name: 'Blood Stain Remover — 25L',
    cat: 'laundry',
    sub: 'Targeted organic stain remover',
    price: 0,
    was: null,
    size: '25L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Bulk industrial enzyme-based stain remover, targeting blood, perspiration, and biological stains across high-capacity wash cycles.',
    benefits: ['Biological stain solver', 'High bulk concentration', 'Improves wash yield', 'Optimized for high-capacity laundries'],
    sku: 'DEMO-LND-029',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },

  // 8. Bleach 5% (5L, 10L, 20L, 25L)
  {
    id: 'demo-bleach-5-percent-5l',
    name: 'Bleach 5% — 5L',
    cat: 'laundry',
    sub: 'Commercial chlorine sanitizing bleach',
    price: 0,
    was: null,
    size: '5L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Multi-purpose sanitizing and whitening chlorine bleach (5% active) for commercial laundry, hotels, and general facility cleaning.',
    benefits: ['Whitens white fabrics', 'Kills 99.9% of bacteria', '5% sodium hypochlorite', 'Effective stain remover & sanitizer'],
    sku: 'DEMO-LND-030',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-bleach-5-percent-10l',
    name: 'Bleach 5% — 10L',
    cat: 'laundry',
    sub: 'Commercial chlorine sanitizing bleach',
    price: 0,
    was: null,
    size: '10L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Commercial sodium hypochlorite bleach (5%) for sanitizing, disinfecting, and brightening linens in school, hospital, and hospitality laundries.',
    benefits: ['Brightens and sanitizes whites', 'Industrial disinfection strength', 'Multi-surface sanitizing compatible', 'Consistent chlorine level'],
    sku: 'DEMO-LND-031',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-bleach-5-percent-20l',
    name: 'Bleach 5% — 20L',
    cat: 'laundry',
    sub: 'Commercial chlorine sanitizing bleach',
    price: 0,
    was: null,
    size: '20L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Bulk 5% chlorine bleach for sanitization and stain whitening, ideal for guesthouses, cleaning services, and professional laundries.',
    benefits: ['Excellent stain oxidation', 'High-volume sanitizing', 'Cost-effective whitening', 'Multi-purpose facility use'],
    sku: 'DEMO-LND-032',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-bleach-5-percent-25l',
    name: 'Bleach 5% — 25L',
    cat: 'laundry',
    sub: 'Commercial chlorine sanitizing bleach',
    price: 0,
    was: null,
    size: '25L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Industrial bulk 5% sodium hypochlorite bleach, optimized for chemical dosing systems in commercial laundries and large facilities.',
    benefits: ['Industrial bulk value', 'Consistent 5% active chlorine', 'Highly effective sanitization', 'Perfect for commercial dosing pumps'],
    sku: 'DEMO-LND-033',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },

  // 9. Bio Thick Bleach (5L, 10L, 20L, 25L)
  {
    id: 'demo-bio-thick-bleach-5l',
    name: 'Bio Thick Bleach — 5L',
    cat: 'laundry',
    sub: 'Thickened bioactive sanitizing bleach',
    price: 0,
    was: null,
    size: '5L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Thickened disinfectant bleach with sanitizing bio-active properties. Clings to surfaces and provides superior sanitization in guesthouses and laundries.',
    benefits: ['Clings for longer contact', 'Kills pathogens & mold', 'Thickened active formula', 'Dual use for laundry and surfaces'],
    sku: 'DEMO-LND-034',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-bio-thick-bleach-10l',
    name: 'Bio Thick Bleach — 10L',
    cat: 'laundry',
    sub: 'Thickened bioactive sanitizing bleach',
    price: 0,
    was: null,
    size: '10L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Concentrated thick bleach with powerful germ-kill action and surface adherence, perfect for commercial restroom hygiene and laundry bleach steps.',
    benefits: ['Extended contact clinging', 'Superior sanitization control', 'Deep cleaning & whitening', 'Suitable for high-use facilities'],
    sku: 'DEMO-LND-035',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-bio-thick-bleach-20l',
    name: 'Bio Thick Bleach — 20L',
    cat: 'laundry',
    sub: 'Thickened bioactive sanitizing bleach',
    price: 0,
    was: null,
    size: '20L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Bulk thick sanitizing bleach formulated for heavy-duty hospital, school, and hotel disinfection and commercial laundry whitening.',
    benefits: ['High surface adherence', 'Industrial hygiene solution', 'Brightens white bedding & linen', 'Powerful bio-sanitizer'],
    sku: 'DEMO-LND-036',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-bio-thick-bleach-25l',
    name: 'Bio Thick Bleach — 25L',
    cat: 'laundry',
    sub: 'Thickened bioactive sanitizing bleach',
    price: 0,
    was: null,
    size: '25L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Maximum-volume industrial thick bleach for commercial cleaning contractors and laundries, offering strong disinfection and clinging power.',
    benefits: ['Bulk contractor size', 'Strong germicide & sanitizer', 'Thickened active cling formulation', 'Whitens bulk textiles'],
    sku: 'DEMO-LND-037',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },

  // 10. ABL Stain Remover (5L, 10L, 20L, 25L)
  {
    id: 'demo-abl-stain-remover-5l',
    name: 'ABL Stain Remover — 5L',
    cat: 'laundry',
    sub: 'High-strength laundry pre-wash stain remover',
    price: 0,
    was: null,
    size: '5L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'High-strength laundry spot and stain pre-treatment spray/wash, safe for colors and whites. Ideal for removing food, grease, and ink in guesthouses.',
    benefits: ['High-strength spotter', 'Color-safe formula', 'Removes grease, food & ink', 'Easy pre-wash application'],
    sku: 'DEMO-LND-038',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-abl-stain-remover-10l',
    name: 'ABL Stain Remover — 10L',
    cat: 'laundry',
    sub: 'High-strength laundry pre-wash stain remover',
    price: 0,
    was: null,
    size: '10L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Commercial fabric stain remover concentrate, targeting heavy soil and collar marks for boutique hotels and guesthouse laundries.',
    benefits: ['Targets collar & cuff soil', 'Concentrated stain pre-soak', 'Saves fabrics from heavy stains', 'Fast acting formula'],
    sku: 'DEMO-LND-039',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-abl-stain-remover-20l',
    name: 'ABL Stain Remover — 20L',
    cat: 'laundry',
    sub: 'High-strength laundry pre-wash stain remover',
    price: 0,
    was: null,
    size: '20L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Industrial laundry stain remover for commercial laundry operations, lifting grease, grime, cosmetics, and beverage stains in volume.',
    benefits: ['Strips oil & makeup traces', 'Improves first-wash stain removal', 'Designed for high volume sorting', 'Protects fabric integrity'],
    sku: 'DEMO-LND-040',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
  {
    id: 'demo-abl-stain-remover-25l',
    name: 'ABL Stain Remover — 25L',
    cat: 'laundry',
    sub: 'High-strength laundry pre-wash stain remover',
    price: 0,
    was: null,
    size: '25L',
    rating: 0,
    reviews: 0,
    badge: null,
    img: '',
    desc: 'Bulk commercial pre-wash stain remover, designed for industrial garment washers, laundries, and hospitality linen restoration.',
    benefits: ['Bulk pre-treatment sizing', 'Powerful industrial action', 'Restores heavily stained linens', 'Cost-effective laundry spotter'],
    sku: 'DEMO-LND-041',
    stock: 10,
    lowStockThreshold: 5,
    status: 'active',
    purchaseMode: 'quote',
    whatsappEnabled: true,
    variants: [],
    media: [],
  },
];

function safeCompare(a = '', b = '') {
  const left = Buffer.from(String(a));
  const right = Buffer.from(String(b));
  return left.length === right.length && timingSafeEqual(left, right);
}

export async function GET(req) {
  const url = new URL(req.url);
  const secret = url.searchParams.get('secret');

  if (!process.env.SEED_SECRET) {
    return NextResponse.json({ error: 'SEED_SECRET not configured.' }, { status: 500 });
  }

  if (!secret || !safeCompare(secret, process.env.SEED_SECRET)) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
  }

  try {
    await connectToDatabase();

    const catOp = {
      updateOne: {
        filter: { id: LAUNDRY_CATEGORY.id },
        update: { $setOnInsert: { ...LAUNDRY_CATEGORY, createdAt: Date.now() } },
        upsert: true,
      },
    };
    const catResult = await Category.bulkWrite([catOp], { ordered: false });

    const productOps = LAUNDRY_PRODUCTS.map(p => ({
      updateOne: {
        filter: { id: p.id },
        update: { $set: { ...p, updatedAt: Date.now() } },
        upsert: true,
      },
    }));
    const productResult = await Product.bulkWrite(productOps, { ordered: false });

    return NextResponse.json({
      success: true,
      category: {
        upserted: catResult.upsertedCount,
        matched: catResult.matchedCount,
      },
      products: {
        upserted: productResult.upsertedCount,
        modified: productResult.modifiedCount,
        matched: productResult.matchedCount,
      },
    });
  } catch (err) {
    console.error('[/api/seed-laundry] Failed:', err);
    return NextResponse.json({ error: 'Seed failed', message: err.message }, { status: 500 });
  }
}
